const dictionary = {
  accountant: "muhasebeci",
  afraid: "korkmuş",
  age: "yaş",
  airplane: "uçak",
  alone: "yalnız",
  angry: "kızgın-sinirli",
  animal: "hayvan",
  answer: "cevap vermek",
  architect: "mimar",
  arrive: "varmak",
  aunt: "hala-teyze",
  bag: "çanta",
  ball: "top",
  bath: "banyo",
  beautiful: "güzel",
  bill: "hesap-fatura",
  body: "vücut",
  boil: "kaynamak",
  bookstore: "kitapçı",
  boring: "sıkıcı",
  borrow: "ödünç almak",
  boss: "patron",
  bottle: "şişe",
  box: "kutu",
  brave: "cesur",
  bread: "ekmek",
  break: "kırmak",
  bridge: "köprü",
  brush: "fırça",
  build: "inşa etmek",
  butter: "tere yağı",
  calculator: "hesap makinası",
  calendar: "takvim",
  call: "aramak",
  capital: "başkent",
  carpenter: "marangoz",
  carpet: "halı",
  carry: "taşımak",
  cartoon: "çizgi film",
  chair: "sandalye",
  cheap: "ucuz",
  cheese: "peynir",
  cherry: "kiraz",
  chicken: "tavuk",
  church: "kilise",
  clean: "temizlemek",
  clear: "açık, net",
  clever: "akıllı",
  clock: "saat",
  cloud: "bulut",
  coat: "kaban",
  cold: "soğuk",
  company: "şirket",
  continue: "devam etmek",
  correct: "doğru",
  country: "ülke",
  cow: "inek",
  cry: "ağlamak",
  daily: "günlük",
  dark: "koyu-karanlık",
  dentist: "diş hekimi",
  difficult: "zor",
  dirty: "kirli",
  divorced: "boşanmış",
  draw: "çizmek",
  early: "erken",
  earn: "kazanmak",
  elephant: "fil",
  emergency: "acil",
  empty: "boş",
  engaged: "nişanlı",
  engineer: "mühendis",
  enough: "yeterli",
  eraser: "silgi",
  error: "hata",
  fall: "düşmek-sonbahar",
  far: "uzak",
  farm: "çiftlik",
  fat: "şişman",
  finger: "parmak",
  fire: "ateş-yangın",
  flight: "uçuş",
  floor: "yer,zemin",
  fork: "çatal",
  friendly: "arkadaşça",
  fruit: "meyve",
  funny: "komik",
  garden: "bahçe",
  glass: "bardak",
  grape: "üzüm",
  gun: "tabanca",
  habit: "alışkanlık",
  half: "yarım",
  hand: "el",
  handsome: "yakışıklı",
  hate: "nefret etmek",
  health: "sağlık",
  hear: "duymak",
  heart: "kalp",
  heavy: "ağır",
  high: "yüksek",
  history: "tarih",
  horror: "korku",
  hungry: "aç",
  ill: "hasta",
  interested: "ilgili",
  job: "meslek",
  journalist: "gazeteci",
  kill: "öldürmek",
  large: "geniş",
  laugh: "gülmek",
  lawyer: "avukat",
  leave: "ayrılmak",
  lend: "ödünç vermek",
  letter: "mektup",
  library: "kütüphane",
  light: "hafif / ışık",
  lunch: "öğle yemeği",
  main: "ana-temel",
  manager: "yönetici,müdür",
  map: "harita",
  married: "evli",
  meal: "yemek",
  meet: "buluşmak",
  meeting: "toplantı",
  melon: "kavun",
  minute: "dakika",
  mirror: "ayna",
  miss: "özlemek",
  month: "ay",
  need: "ihtiyaç",
  neighbour: "komşu",
  news: "haberler",
  nice: "hoş",
  nose: "burun",
  nurse: "hemşire",
  object: "nesne",
  opposite: "karşı-zıt",
  oven: "fırın",
  page: "sayfa",
  paint: "boyamak",
  parent: "ebeveyn",
  pass: "geçmek",
  pay: "ödemek",
  pepper: "biber",
  personal: "kişisel",
  pet: "evcil hayvan",
  place: "yer",
  plane: "uçak",
  pocket: "cep",
  polite: "kibar",
  pool: "havuz",
  poor: "fakir",
  possible: "mümkün",
  push: "ittirmek",
  quick: "hızlı",
  quiet: "sessiz",
  railway: "tren yolu",
  ready: "hazır",
  refrigerator: "buzdolabı",
  remember: "hatırlamak",
  rent: "kiralamak",
  repair: "tamir etmek",
  repeat: "tekrar etmek",
  restroom: "tuvalet",
  return: "geri dönmek",
  rice: "pirinç",
  rich: "zengin",
  ride: "binmek",
  right: "doğru",
  ring: "yüzük-telefonun çalması",
  rise: "güneş(doğmak)",
  river: "ırmak",
  road: "yol",
  roof: "çatı",
  room: "oda",
  rose: "gül",
  salt: "tuz",
  same: "aynı",
  security: "güvenlik",
  sell: "satmak",
  serious: "ciddi",
  shelf: "raf",
  ship: "gemi",
  shirt: "gömlek",
  shoe: "ayakkabı",
  show: "göstermek",
  sick: "hasta",
  sing: "şarkı söylemek",
  single: "bekar",
  skirt: "etek",
  sky: "gökyüzü",
  smile: "gülümsemek",
  snow: "kar",
  socks: "çorap",
  son: "oğul",
  song: "şarkı",
  soup: "çorba",
  spend: "harcamak",
  spoon: "kaşık",
  stamp: "pul",
  stay: "kalmak",
  story: "hikaye",
  strawberry: "çilek",
  strong: "güçlü",
  successful: "başarılı",
  suit: "takım elbise",
  sweet: "tatlı",
  talk: "konuşmak",
  tall: "uzun",
  teach: "öğretmek",
  thick: "kalın",
  thief: "hırsız",
  thin: "zayıf",
  think: "düşünmek",
  thirsty: "susamış",
  ticket: "bilet",
  tidy: "düzenlemek",
  tired: "yorgun",
  toothbrush: "diş fırçası",
  toothpaste: "diş macunu",
  towel: "havlu",
  tower: "kule",
  town: "kasaba",
  toy: "oyuncak",
  trainers: "spor ayakkabı",
  travel: "seyahat",
  tree: "ağaç",
};

const ingilizce = document.getElementById("en");
const türkçe = document.getElementById("tr");
const show = document.getElementById("show");
const next = document.getElementById("next");

const dizeyeÇevirme = Object.entries(dictionary);

next.addEventListener("click", () => {
  const mathRandom = Math.floor(Math.random() * dizeyeÇevirme.length);
  ingilizce.textContent = dizeyeÇevirme[mathRandom][0];
  türkçe.textContent = dizeyeÇevirme[mathRandom][1];
  dizeyeÇevirme.splice(mathRandom, 1);
});

show.addEventListener("click", () => {
  türkçe.classList.toggle("hide");
});
